# Generated by Django 5.1.6 on 2025-08-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
