# Generated by Django 5.1.6 on 2025-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_question_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='userskill',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
