# Generated by Django 5.1.6 on 2025-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_skill_category_userskill_is_onboarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='is_onboarded',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
