# Generated by Django 5.1.6 on 2025-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizresult',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
